# action.yml
name: 'Create PDF'
description: 'Creates PDF files from github markdown'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/tactiq-hq/actions-makepdfs/actions-makepdfs:configurable-page-breaks'

inputs:
  markdown_dir:
    description: 'Location of markdown files in github repository'
    required: true
    default: 'doc'
  output_dir:
    description: 'Location to output PDF files to'
    required: true
    default: 'tmp'
  additional_css:
    description: 'For additional raw CSS'
    required: false
    default: ''

branding:
  icon: 'activity'
  color: 'green'
